fortran-lang/webpage

LICENSE
source/conf.py

The current copyright statement states the year 2022, but most of the content was created in 2020 and 2021. This PR updates the copyright years to 2020-2022.

Fix year in the copyright statement

---

source/index.md

There is a spurious break in the "What is the status of Fortran?" section of the FAQ on the landing page. The info is also slightly out-of-date regarding the Fortran 2023 development. This PR fixes that.

Update the Fortran status paragraph

---

source/compilers.md

This PR is to add the  LFortran WASM compiler to the compilers section of the fortran-lang.org , we should reference the LFortran WASM compiler to make it more discoverable for visitors.  please refer #46 for more information.
Please provide your suggestions regarding the current description of the compiler and location of the link in the webpage.
Thanks and Regards,
Henil Shalin Panchal
CC @awvwgk @certik @Shaikh-Ubaid

Link to LFortran WASM compiler #46 

---

data/learning.yml

- Concerning WG5, as the `description:` field is void, the "None" string appeared on the webpage. I have removed that field to avoid that.
- I have deleted a ")" without a corresponding "("

Fixes two typos in the Learn page

---

locale/cs/LC_MESSAGES/index.po
locale/de/LC_MESSAGES/index.po
locale/es/LC_MESSAGES/index.po
locale/fr/LC_MESSAGES/index.po
locale/ja/LC_MESSAGES/index.po
locale/nl/LC_MESSAGES/index.po
locale/pt/LC_MESSAGES/index.po
locale/zh_CN/LC_MESSAGES/index.po
source/learn.md
source/learn/best_practices/index.md
source/learn/building_programs/build_tools.md
source/learn/building_programs/include_files.md
source/learn/building_programs/index.md
source/learn/building_programs/linking_pieces.md
source/learn/building_programs/managing_libraries.md
source/learn/os_setup/index.md
source/learn/quickstart/index.md
source/learn/quickstart/variables.md

Thank you for the tutorial. I am new at Fortran (I only wrote python before) and found the tutorial helpful.
But the tutorial toctree is alphabetical. I adjust the title order in https://fortran-lang.org/en/learn/quickstart/ sidebar
based on https://github.com/fortran-lang/webpage/blob/main/data/learning.yml.
I also fix some typos in my reading.
Welcome review. I am happy to modify if something I did wrong.

Adjust title order in learning toctree and fix some typos

---

Makefile
locale/ru/LC_MESSAGES/index.po
source/_templates/version-switcher.html

This pull request introduce Russian translation of **webpage**, namely `index`, `learn`, `learn/quickstart/*` pages.
Attached zip tarball ([fortran-lang-org_ru_initial.zip](https://github.com/fortran-lang/webpage/files/9679432/fortran-lang-org_ru_initial.zip)) contains pdf-pages of built version of translated **webpage** for preview.
P.S.
`Makefile`: is also updated here.  
`source/_templates/version-switcher.html`: The additional `comma` in this file was added by `prettier` hook.

Add/Update initial Russian translation

---

source/index.md
source/learn.md

The Fortran-lang playground (https://github.com/fortran-lang/playground) should be linked from the webpage to make it easier to discover. Please refer #44   for more details. 
Possible options are:
- in the top navigation bar
- in the compiler section next to the supported compilers
CC @awvwgk @ashirrwad, @everythingfunctional @milancurcic

Link to online compiler playground #44

---

.gitignore
source/index.md
source/roadmap.md

A roadmap for the Fortran-lang Organization and its individual repos.
I left the fpm-ize project in, even though we had a GSoC project on this since we can/should always strive to port more projects to fpm (especially commonly used scientific software)

doc: add fortran-lang roadmap

---

data/package_index.yml

Adds Fortnet to the package index.
I confirm the following package criteria:

Add Fortnet to package index

---

source/learn/intrinsics/_pages/NEW_LINE.md

This fixes a broken code block that was causing the page to display incorrectly.
It also removes an extra `` ` `` from the code block below.

Fix formatting in description for NEW_LINE

---

source/learn/rosetta_stone.md

This is a fix for #291.
There were two similar options. I removed the first and kept the second. If the opposite alternative is preferable, just let me know.

fix: remove repeated example of loop between indexes i and j

---

source/learn/quickstart/variables.md

Not sure where this came from. I see a couple instances of "content=" in some markup tags elsewhere in the repo so maybe some copypasta.
Either way I think it's clearer to just remove it.

Removed confusing wording in intro docs

---

source/community/contributing.md

In line 59 of source/community/contributing.md, it mentions README.md and links to it. However, the link is broken due to "blob" and "HEAD" in the URL being in the wrong order. I switched them around so that it actually works.

Fix broken link to README.md in contributing.md

---

source/learn/best_practices/arrays.md
source/learn/building_programs/build_tools.md
source/learn/quickstart/index.md

The 1st commit fix urls to make it visible (arrays url)  and working (cmake url).  
The 2nd remove paragrath about absent button.

fix URLs (for CMake and Arrays sections) and Quickstart confusing paragraph

---

data/package_index.yml

The gFTL library is currently shown in the category "Error handling, logging, documentation and testing" but it is tagged as "container". It should be in the category "Libraries for advanced data types and container classes" along with the similar package Fortran template library (FTL).

Correct gFTL package category

---

data/package_index.yml

We would like to add FTorch, a python library for directly interfacing from Fortran to PyTorch Machine Learning models, to the Fortran-Lang website.
This has been developed and deployed in a number of scientific codes.
I believe it meets the core requirements set out [here](https://fortran-lang.org/en/community/packages/#package-criteria).
The project is still being actively developed, but we are at a point where we feel it is of use to other developers.
The project is at https://github.com/Cambridge-ICCS/FTorch
There are some associated slides [here](https://jackatkinson.net/slides/RSECon23/RSECon23.html).
I couldn't fine a package PR template, but please do point me in the right direction if I missed it.
Thanks.

Add FTorch to Package Index

---

source/learn/building_programs/build_tools.md

This request offers the extension of `Learn - Building programs - Build Tools` with information about SCons build system. I don't use this build system (I see it only on packaging of Cantera), but the information about it might be interesting. Maybe the info about additional syntax of source files list representation is excessive.
The language of text definitely needs editing.
P.S.  
Additional commit is to fix URLs.

Learn: Build tools: add 'The SCons build system' section

---

source/compilers.md

The link to the CCE is 404. I have provided an updated link to the CCE.

Fix link to Cray Compiling Environment

---

source/learn/os_setup/text_editors.md

The notepad3 link has been added in the text_editors.md below visual studio code.

Notepad3 Link added

---

data/package_index.yml

Adds [preCICE](https://precice.org/) to the categories `interfaces` and `scientific`.
preCICE is written in C++, but it has [bindings for Fortran and more languages](https://precice.org/couple-your-code-api.html).
Thanks to @ivan-pi for showing me this package index.

Add preCICE library to the package index

---

source/index.md
source/learn.md

This fixes the issue at https://fortran-lang.discourse.group/t/fortran-playground-broken-play-fortran-lang-org/7788.

Use dev.lfortran.org for the playground for now

---

source/learn/quickstart/derived_types.md

This attribute apparently did not make it into Fortran 2023, but is still shown on the Fortran Quickstart page
See https://fortran-lang.discourse.group/t/protected-attribute-for-derived-type-components/7360

Remove 'protected' derived-type member attribute from Quickstart

---

data/package_index.yml

Add [athena](https://github.com/nedtaylor/athena) to the `numerical` category.
I believe it conforms with all of the [package criteria](https://fortran-lang.org/community/packages/).
I was unable to find the 'Package index request' template mentioned on step 3 of the process for adding packages. If this is needed, please direct me to it and I will use that instead.

Add athena entry to package index

---

data/package_index.yml

Add [RAFFLE](https://github.com/ExeQuantCode/RAFFLE) to the Scientific category.
I believe it conforms with all of the [package criteria](https://fortran-lang.org/community/packages/).

Add raffle to the package index

---

data/package_index.yml

This PR adds [Fortitude](https://github.com/PlasmaFAIR/Fortitude) to the package index.
- Relevance: This is a Fortran linting tool, though is written in Rust. There are plans to add formatting functionality in the near-future.
- Maturity: Though fairly new, the repo has 70 stars and is still climbing in popularity.
- Availability: The source is freely available on GitHub.
- Open source: The package is licensed under MIT.
- Uniqueness: :white_check_mark: 
- README: States the purpose of the package, explains installation and usage, and links to more thorough documentation.
- Documentation: https://fortitude.readthedocs.io/en/stable/
- Contributing: https://github.com/PlasmaFAIR/fortitude/blob/main/CONTRIBUTING.md
- Tests: :white_check_mark:

Add Fortitude to the package index

---

data/package_index.yml

It looks like it should just be fortran-lang/test-drive, not https://github.com/fortran-lang/test-drive.
Fixes #536.

Fix Git repo for test-drive project

---

data/learning.yml
fortran_package.py
source/learn.md

Several updates to the 'learn' page
1. Several of the links in the 'online courses' section were dead. They have been removed
2. A new category 'training providers' has been added, linking to places where in-person/remote courses are advertised. 
3. Existing links to 'online courses' have been split. Several constitute ebooks, so a new heading is added for those. The others now contain in the description a 'type', e.g. (video), (sample code), (course slides).
Depending on whether the [policy for including commercial _packages_](https://fortran-lang.discourse.group/t/commercial-packages-referenced-by-fortran-lang-org/9554/2) is changed, it may be appropriate to add in some additional training providers.

Update 'learn' page

---

data/package_index.yml

Fixes for a couple of errors in the package index.

Fix errors and remove redundant fields

---

source/packages/data-types.md
source/packages/examples.md
source/packages/graphics.md
source/packages/interfaces.md
source/packages/io.md
source/packages/libraries.md
source/packages/numerical.md
source/packages/programming.md
source/packages/scientific.md
source/packages/strings.md

Fixes https://github.com/fortran-lang/webpage/issues/553
Part of the [Fortran Index](https://github.com/fortran-index/fortran-index) project (https://github.com/fortran-index/fortran-index/issues/23)
---
If a license field is provided in `package_index.yml`, the license badge is generated using the [shields.io static badge generator](https://shields.io/badges/static-badge). This fixes numerous packages which display licenses as "not identifiable by github" and packages hosted on BitBucket (or elsewhere) that currently don't display any license info.

Display package license info if provided in `package_index.yml`

---

data/package_index.yml

This PR adds https://github.com/Nicholaswogan/Differentia to the package index.
- Relevance - This is a package allowing for derivatives, gradients and Jacobians of Fortran functions/subroutines to be calculated using Forward Automatic Differentiation
- Maturity - the code is stable and the repo is actively developed.
Availability - the source is freely available on GitHub.
- Open source - the package is licensed under MIT License.
- Uniqueness - this is an original repo, not a fork.
- README - this exists, clearly states the purpose, and contains information on the steps required to install, as well as a link to build the code and run the tests
- Tests: the code is well tested, with tests being easy to run
- FPM: supports installation via [fpm](https://github.com/fortran-lang/fpm) via …

Add Differentia package to index

---

source/learn/oop_features_in_fortran/object_based_programming_techniques.md

A correction based on Beliavsky's reading.[1]
[1] https://github.com/fortran-lang/webpage/issues/526

fix(object_based_programming_techniques.md): correct typos

---

data/package_index.yml

Add package [geoschem](https://github.com/geoschem) to the packages list
Fulfils criteria: 
- Relevance - Climate modelling software in use by many research groups
- Maturity - in development since at least 2007 , 176 github stars, 100+ publications found with google scholar
- Availability - via github
- Open source - MIT license
- Uniqueness - this is the source code from the geoschem team
- README - Exists, describes, links to further docs.  
- Documentation -  More documentation on its web pages https://geos-chem.readthedocs.io/en/stable/ : Contributing guidelines , examples

Add Geoschem to packages list

---

locale/de/LC_MESSAGES/index.po
locale/es/LC_MESSAGES/index.po
locale/pt/LC_MESSAGES/index.po
locale/zh_CN/LC_MESSAGES/index.po
source/conf.py
source/roadmap.md

Fix broken links by removing /en from fortran-lang.org URLs

---

source/learn/building_programs/build_tools.md

I wonder if we should have a "minibook" section where we go into more detail?

add brief intro to FPM

---

data/intrinsics.yml
source/learn/intrinsics/_pages/CSHIFT.md

In the intrinsics pages, there were some duplicated entries. See
More over, in some pages of intrinsics, the table of contents does not appear (I do not know why). 
This is the case for
- intrinsics/array,
- intrinsics/character,
- intrinsics/system,

Delete duplicated entries

---

data/package_index.yml

This PR adds several packages to the index and updates existing ones slightly.

Add and update packages
