fortran-lang/webpage

- README.md
- source/community.rst
- source/community/contributing.md
- source/community/minibooks.md
- source/community/packages.md
- source/learn/intrinsics/index.md
- source/packages/data-types.rst
- source/packages/examples.rst
- source/packages/graphics.rst
- source/packages/interfaces.rst
- source/packages/io.rst
- source/packages/libraries.rst
- source/packages/numerical.rst
- source/packages/programming.rst
- source/packages/scientific.rst
- source/packages/strings.rst
> Move contributing, packaging and minibook guidelines to webpage

- source/learn/building_programs/project_make.md
To close https://github.com/fortran-lang/fortran-lang.org/issues/416
> Fix resolution of included files and search paths in minibook

- README.md
- source/learn.md
- source/learn/intrinsics/index.md
> Update link generation in learn pages

- locale/de/LC_MESSAGES/community.po
- locale/de/LC_MESSAGES/index.po
- locale/de/LC_MESSAGES/learn.po
- locale/de/LC_MESSAGES/news.po
- locale/de/LC_MESSAGES/packages.po
- locale/de/LC_MESSAGES/sphinx.po
> German translation of webpage

- locale/de/LC_MESSAGES/index.po
- locale/es/LC_MESSAGES/index.po
- locale/fr/LC_MESSAGES/index.po
- locale/ja/LC_MESSAGES/index.po
- locale/nl/LC_MESSAGES/index.po
- locale/pt/LC_MESSAGES/index.po
- locale/zh_CN/LC_MESSAGES/index.po
- source/learn/building_programs/build_tools.md
- source/learn/quickstart/operators_control_flow.md
- remove two leftover jekyll templates
> Minor fixes

- source/index.md
The sentence "You can learn how to get started here.." should be ended by one dot, not two.
> fix a typo in the last sentence of the homepage

- source/community.md
- source/community/contributing.md
- source/community/minibooks.md
- source/community/packages.md
- source/learn/intrinsics/index.md
- source/learn/os_setup/choose_compiler.md
> Fix links and references

- data/package_index.yml
Added packages, same as in the [pull request for the old repo](https://github.com/fortran-lang/fpm-registry/pull/63).
> Added packages

- .github/workflows/build.yml
See https://fortran-lang.discourse.group/t/4942
> Add step to generate BingSiteAuth.xml

- .github/workflows/build.yml
- requirements.txt
- source/conf.py
This PR is to resolve #222 , Please refer : https://fortran-lang.discourse.group/t/4942 . 
Each sitemap is globalised and has links for all languages ( sitemap.xml in each language is same ) ,  but due to the fixed location for sitemap.xml in extension we had to use the en version .
Thanks and Regards,
Henil
CC @awvwgk @certik
> Add sitemap.xml for crawlers

- source/compilers.md
01 Jan 2023 updates to intel Fortran compiler
> Intel Updates for compilers.md

- source/_templates/layout.html
- source/_templates/version-switcher.html
This PR is to resolve #222 , Please refer : https://fortran-lang.discourse.group/t/4942 . 
This would add a custom meta tag for description and keywords to all the pages of the webpage.
Thanks and Regards,
Henil
CC @awvwgk @certik
> fix meta tags for crawlers

- .gitignore
- source/learn/intrinsics/_pages/ERF.md
- source/learn/intrinsics/_pages/ERFC.md
erf markdown error fix and erfc formula correction
> fix intrinsic math erf and erfc formula errors

- data/package_index.yml
Add descriptions of package MOKIT. Repo: https://gitlab.com/jxzou/mokit
Hoping MOKIT can be added to packages in the scientific code category. Any suggestions are welcomed.
Thank you.
> Add: Fortran package MOKIT, update package_index.yml

- requirements.txt
> maintainance PR

- data/learning.yml
> Added the book "How to learn Applied Mathematics through modern FORTRAN"

- data/package_index.yml
Added an entry describing the qr_mumps package
> Added qr_mumps to package_index.yml

- source/learn/quickstart/variables.md
Proposal to enrich the variables section with the use of the block construct
> Add local variable with block construct

- source/conf.py
> update copyright year

- data/learning.yml
By now, it is the 6th edition which is the most recent available.
> update record "Modern Fortran Explained"

- source/learn/quickstart/variables.md
With some justification, Tsoding https://www.youtube.com/watch?v=PvUQndB8R9s&ab_channel=TsodingDaily mocked the first complete program in the tutorial for not doing a calculation and just echoing the input. So I added a small calculation.
> Add a small calculation to the read_value program

- requirements.txt
- source/_static/data.json
- source/community/history.md
- source/conf.py
updates package Dependencies and fixed the pydata-sphinx-theme version dependency.
I have verified the dependencies.
Thanks and Regards,
Henil
> Maintainance PR feat: fixed the pydata-sphinx-theme version dependency

- source/learn/quickstart/arrays_strings.md
I was re reading some of the materials in the website and though about my early days of Fortran, I would've liked more verbosity in the explanation of how array slicing works and if I had copied and pasted a program that had examples on setting arrays to 0, then certain elements to 1, I would've expected the printing to reflect the operations in the program.
> verbosity in array slicing and examples program 

- data/package_index.yml
MESA has been on github for a few years now. I am updating the records.
> updating mesa records

- data/package_index.yml
FLAME: a library for atomistic modeling environments was added.
> FLAME: a library for atomistic modeling environments was added.

- data/package_index.yml
Add package [PHANTOM](https://github.com/danieljprice/phantom) to the packages list
Fulfils criteria: 
- Relevance - Astrophysics simulation software 
- Maturity - 115 github stars, 364 citations on its paper, active user community
- Availability - via github
- Open source - GPL3 license
- Uniqueness - original code on github
- README - Github readme and further docs on its website https://phantomsph.github.io
> Added package PHANTOM
